// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq6Lz2BaqSiajnYK8zuHTbR9dI3zW2Yl4',
    appId: '1:156547716694:web:e8f483837535c7cf554df7',
    messagingSenderId: '156547716694',
    projectId: 'movies-2aec0',
    authDomain: 'movies-2aec0.firebaseapp.com',
    storageBucket: 'movies-2aec0.firebasestorage.app',
    measurementId: 'G-JLR2F7S6CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Dp8VsFzA3BGPRPJUQkdiCidgl7-rkcU',
    appId: '1:156547716694:android:ac694b868ea73b27554df7',
    messagingSenderId: '156547716694',
    projectId: 'movies-2aec0',
    storageBucket: 'movies-2aec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKA2bOSe07btfJa22YcYrWtOkMvRNkc4',
    appId: '1:156547716694:ios:4a9836172e6999c5554df7',
    messagingSenderId: '156547716694',
    projectId: 'movies-2aec0',
    storageBucket: 'movies-2aec0.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKA2bOSe07btfJa22YcYrWtOkMvRNkc4',
    appId: '1:156547716694:ios:4a9836172e6999c5554df7',
    messagingSenderId: '156547716694',
    projectId: 'movies-2aec0',
    storageBucket: 'movies-2aec0.firebasestorage.app',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq6Lz2BaqSiajnYK8zuHTbR9dI3zW2Yl4',
    appId: '1:156547716694:web:abbc2e2a7c64e8b7554df7',
    messagingSenderId: '156547716694',
    projectId: 'movies-2aec0',
    authDomain: 'movies-2aec0.firebaseapp.com',
    storageBucket: 'movies-2aec0.firebasestorage.app',
    measurementId: 'G-P9SLKLLNCF',
  );
}
